env:
    - GO111MODULE=on
    - GOSUMDB=off
#before:
#    hooks:
#        - go version
#        - go env
#        - rm -rf /build/go.sum
#        - go clean -modcache
#        - go mod download
#gomod:
#    proxy: true
#    env:
#        - GOPROXY=https://goproxy.cn,direct
#        - GOSUMDB=sum.golang.org
builds:
    -   id: windows_amd64
        ldflags: -s -w
        binary: eutamias
        env:
            - CGO_ENABLED=1
            - CC=x86_64-w64-mingw32-gcc
            - CXX=x86_64-w64-mingw32-g++
        main: ./cmd/Eutamias.go
        goos:
            - windows
        goarch:
            - amd64
    -   id: linux_amd64
        ldflags: -s -w
        binary: eutamias
        env:
            - CC=gcc
            - CGO_ENABLED=1
        main: ./cmd/Eutamias.go
        goos:
            - linux
        goarch:
            - amd64
    - id: darwin_amd64
      ldflags: -s -w
      binary: eutamias
      env:
          - CGO_ENABLED=1
          - CC=o64-clang
          - CXX=o64-clang++
      main: ./cmd/Eutamias.go
      goos:
          - darwin
      goarch:
          - amd64
archives:
    - format: tar.gz
      format_overrides:
          - goos: windows
            format: zip
      name_template: "{{.ProjectName}}_v{{.Version}}_{{.Os}}_{{.Arch}}"
      replacements:
          amd64: 64bit
          386: 32bit
          arm: arm
          arm64: arm64
          darwin: macos
          linux: linux
          windows: windows
          openbsd: openbsd
          netbsd: netbsd
          freebsd: freebsd
          dragonfly: dragonflybsd
      files:
          - README.md
          - LICENSE
#          - GeoLite2.mmdb
          - config.yaml
          - ui/**/*
#      allow_different_binary_count: true
checksum:
    name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
    algorithm: sha512
snapshot:
    name_template: "{{ .Tag }}"
#changelog:
#    sort: asc
#    filters:
#        exclude:
#            - '^docs:'
#            - '^test:'
#            - '^dev:'
#            - 'README'
#            - Merge pull request
#            - Merge branch
