project_name: eutamias
env:
    - GO111MODULE=on
    - GOSUMDB=off
    - GOPROXY=https://goproxy.cn,direct
before:
    hooks:
        - go mod tidy
#gomod:
#    proxy: true
#    env:
#        - GO111MODULE=on
#        - GOSUMDB=off
#        - GOPROXY=https://goproxy.cn,direct
builds:
    -   id: windows_amd64
        ldflags:
            - -s -w
            - --extldflags "-static -fpic"
            - -X 'main.UpdateUrl=https://kutt.luoxin.live/0NnXIQ'
            - -X 'geolite.GeoLiteUrl=https://kutt.luoxin.live/GHfTBv'
            - -X 'eutamias.ServiceName={{.ProjectName}}'
            - -X 'proxies.ClashTplUrl=https://kutt.luoxin.live/dxvcRb'
        gcflags:
            - -N -l
        flags:
            - -v
            - -a
        binary: eutamias
        env:
            - CGO_ENABLED=1
            - CC=x86_64-w64-mingw32-gcc
            - CXX=x86_64-w64-mingw32-g++
        main: ./cmd/eutamias.go
        goos:
            - windows
        goarch:
            - amd64
    -   id: linux_amd64
        ldflags:
            - -s -w
            - --extldflags "-static -fpic"
            - -X 'main.UpdateUrl=https://kutt.luoxin.live/dDh0c5'
            - -X 'geolite.GeoLiteUrl=https://kutt.luoxin.live/GHfTBv'
            - -X 'eutamias.ServiceName={{.ProjectName}}'
            - -X 'proxies.ClashTplUrl=https://kutt.luoxin.live/dxvcRb'
        gcflags:
            - -N -l
        flags:
            - -v
            - -a
        binary: eutamias
        env:
            - CC=gcc
            - CGO_ENABLED=1
        main: ./cmd/eutamias.go
        goos:
            - linux
        goarch:
            - amd64
    #    -   id: darwin_amd64
    #        ldflags:
    #            - -s -w
    #            - --extldflags "-static -fpic"
    #            - -X 'main.UpdateUrl=https://kutt.luoxin.live/gloV0B'
    #            - -X 'geolite.GeoLiteUrl=https://kutt.luoxin.live/GHfTBv'
    #            - -X 'eutamias.ServiceName={{.ProjectName}}'
    #            - -X 'proxies.ClashTplUrl=https://kutt.luoxin.live/dxvcRb'
    #        gcflags:
    #            - -N -l
    #        flags:
    #            - -v
    #            - -a
    #        binary: eutamias
    #        env:
    #            - CGO_ENABLED=1
    #            - CC=o64-clang
    #            - CXX=o64-clang++
    #        main: ./cmd/eutamias.go
    #        goos:
    #            - darwin
    #        goarch:
    #            - amd64
    -   id: checkwall
        ldflags:
            - -s -w
        gcflags:
            - -N -l
        flags:
            - -v
            - -a
        binary: checkwall
        env:
            - CGO_ENABLED=0
        main: ./tool/checkwall/checkwall.go
        goos:
            - linux
            - windows
        goarch:
            - amd64
archives:
    -   format: tar.gz
        format_overrides:
            -   goos: windows
                format: zip
        name_template: "{{.ProjectName}}_v{{.Version}}_{{.Os}}_{{.Arch}}_{{.ShortCommit}}_{{.CommitTimestamp}}"
        replacements:
            amd64: 64bit
            386: 32bit
            arm: arm
            arm64: arm64
            darwin: macos
            linux: linux
            windows: windows
            openbsd: openbsd
            netbsd: netbsd
            freebsd: freebsd
            dragonfly: dragonflybsd
        files:
            - README.md
            - LICENSE
            - resource/GeoLite2.mmdb
            - config.yaml
            - ui/**/*
            - resource/clashTpl
#        allow_different_binary_count: true
checksum:
    name_template: "eutamias_v{{ .Version }}_{{.ShortCommit}}_{{.CommitTimestamp}}_checksums.txt"
    algorithm: sha512
snapshot:
    name_template: "{{ .Tag }}"
source:
    enabled: true
    name_template: '{{ .ProjectName }}_v{{.Version}}_{{.ShortCommit}}_{{.CommitTimestamp}}'
changelog:
    skip: false
    sort: asc
    filters:
        exclude:
            - 'fix'
            - 'docker'
            - 'make'
            - 'tpl'
            - 'clash tpl'
            - 'config'
            - 'release'
            - 'upmod'
            - 'update'
            - 'start'
            - 'linit'
            - 'log'
            - 'go mod'
            - 'Makefile'
            - 'dockerfile'
            - 'gen'
            - 'go release'
            - 'rule'
#    filters:
#        - exclude:
#            - '^docs:' e
#            - '^test:'
#            - '^dev:'
#            - 'README'
#            - Merge pull request
#            - Merge branch
