env:
    - GO111MODULE=on
before:
    hooks:
        - go version
#        - go clean -modcache
#        - rm -rf ./go.sum
#        - go mod tidy
#gomod:
#    proxy: true
#    env:
#        - GOPROXY=https://goproxy.cn,direct
#        - GOSUMDB=sum.golang.org
builds:
    -   id: windows_windows_amd64
        ldflags: -s -w
        binary: windows
        env:
            - CGO_ENABLED=1
            - CC=x86_64-w64-mingw32-gcc
            - CXX=x86_64-w64-mingw32-g++
        main: ./cmd/windows.go
        goos:
            - windows
        goarch:
            - amd64
    - id: windows_darwin_amd64
      ldflags: -s -w
      binary: windows
      env:
          - CGO_ENABLED=1
          - CC=o64-clang
          - CXX=o64-clang++
      main: ./cmd/windows.go
      goos:
          - darwin
      goarch:
          - amd64
#      flags:
#          - -mod=vendor
    - id: windows_linux_amd64
      ldflags: -s -w
      binary: windows
      env:
          - CC=gcc
          - CGO_ENABLED=1
      main: ./cmd/windows.go
      goos:
          - linux
      goarch:
          - amd64
archives:
    - format: tar.gz
      format_overrides:
          - goos: windows
            format: zip
      name_template: "{{.ProjectName}}_v{{.Version}}_{{.Os}}_{{.Arch}}"
      replacements:
          amd64: 64bit
          386: 32bit
          arm: arm
          arm64: arm64
          darwin: macos
          linux: linux
          windows: windows
          openbsd: openbsd
          netbsd: netbsd
          freebsd: freebsd
          dragonfly: dragonflybsd
      files:
          - README.md
          - LICENSE
          - GeoLite2.mmdb
          - config.yaml
checksum:
    name_template: "{{.ProjectName}}_v{{.Version}}_{{.Os}}_{{.Arch}}_checksums.txt"
    algorithm: sha512
snapshot:
    name_template: "{{ .Tag }}"
changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
            - '^dev:'
            - 'README'
            - Merge pull request
            - Merge branch
