// Code generated by protoc-gen-go. DO NOT EDIT.
// source: subscription.proto

package subscription

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrCode int32

const (
	ErrCode_Success ErrCode = 0
)

var ErrCode_name = map[int32]string{
	0: "Success",
}
var ErrCode_value = map[string]int32{
	"Success": 0,
}

func (x ErrCode) String() string {
	return proto.EnumName(ErrCode_name, int32(x))
}
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_subscription_af37a71ad6fa795b, []int{0}
}

type CrawlType int32

const (
	CrawlType_CrawlTypeNil           CrawlType = 0
	CrawlType_CrawlTypeSubscription  CrawlType = 1
	CrawlType_CrawlTypeXpath         CrawlType = 2
	CrawlType_CrawlTypeFuzzyMatching CrawlType = 3
)

var CrawlType_name = map[int32]string{
	0: "CrawlTypeNil",
	1: "CrawlTypeSubscription",
	2: "CrawlTypeXpath",
	3: "CrawlTypeFuzzyMatching",
}
var CrawlType_value = map[string]int32{
	"CrawlTypeNil":           0,
	"CrawlTypeSubscription":  1,
	"CrawlTypeXpath":         2,
	"CrawlTypeFuzzyMatching": 3,
}

func (x CrawlType) String() string {
	return proto.EnumName(CrawlType_name, int32(x))
}
func (CrawlType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_subscription_af37a71ad6fa795b, []int{1}
}

type ProxyNodeType int32

const (
	ProxyNodeType_ProxyNodeTypeNil    ProxyNodeType = 0
	ProxyNodeType_ProxyNodeTypeVmess  ProxyNodeType = 1
	ProxyNodeType_ProxyNodeTypeTrojan ProxyNodeType = 2
	ProxyNodeType_ProxyNodeTypeVless  ProxyNodeType = 3
)

var ProxyNodeType_name = map[int32]string{
	0: "ProxyNodeTypeNil",
	1: "ProxyNodeTypeVmess",
	2: "ProxyNodeTypeTrojan",
	3: "ProxyNodeTypeVless",
}
var ProxyNodeType_value = map[string]int32{
	"ProxyNodeTypeNil":    0,
	"ProxyNodeTypeVmess":  1,
	"ProxyNodeTypeTrojan": 2,
	"ProxyNodeTypeVless":  3,
}

func (x ProxyNodeType) String() string {
	return proto.EnumName(ProxyNodeType_name, int32(x))
}
func (ProxyNodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_subscription_af37a71ad6fa795b, []int{2}
}

type CrawlerConf struct {
	Id        uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CreatedAt uint32 `protobuf:"varint,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt uint32 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	// @gorm: type:varchar(1000);unique_index:idx_crawl_url
	CrawlUrl  string `protobuf:"bytes,4,opt,name=crawl_url,json=crawlUrl" json:"crawl_url,omitempty"`
	CrawlType uint32 `protobuf:"varint,5,opt,name=crawl_type,json=crawlType" json:"crawl_type,omitempty"`
	// @gorm: type:json
	Rule *CrawlerConf_Rule `protobuf:"bytes,6,opt,name=rule" json:"rule,omitempty"`
	// @grom: index: idx_next_crawl_at
	IsClosed bool `protobuf:"varint,7,opt,name=is_closed,json=isClosed" json:"is_closed,omitempty"`
	// @grom: index: idx_next_crawl_at
	NextAt   uint32 `protobuf:"varint,8,opt,name=next_at,json=nextAt" json:"next_at,omitempty"`
	Interval uint32 `protobuf:"varint,9,opt,name=interval" json:"interval,omitempty"`
	// @gorm: type:varchar(100)
	// @v: max=100
	Note                 string   `protobuf:"bytes,10,opt,name=note" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" gorm:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" gorm:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" gorm:"-"`
}

func (m *CrawlerConf) Reset()         { *m = CrawlerConf{} }
func (m *CrawlerConf) String() string { return proto.CompactTextString(m) }
func (*CrawlerConf) ProtoMessage()    {}
func (*CrawlerConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_subscription_af37a71ad6fa795b, []int{0}
}
func (m *CrawlerConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlerConf.Unmarshal(m, b)
}
func (m *CrawlerConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlerConf.Marshal(b, m, deterministic)
}
func (dst *CrawlerConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlerConf.Merge(dst, src)
}
func (m *CrawlerConf) XXX_Size() int {
	return xxx_messageInfo_CrawlerConf.Size(m)
}
func (m *CrawlerConf) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlerConf.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlerConf proto.InternalMessageInfo

func (m *CrawlerConf) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CrawlerConf) GetCreatedAt() uint32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *CrawlerConf) GetUpdatedAt() uint32 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *CrawlerConf) GetCrawlUrl() string {
	if m != nil {
		return m.CrawlUrl
	}
	return ""
}

func (m *CrawlerConf) GetCrawlType() uint32 {
	if m != nil {
		return m.CrawlType
	}
	return 0
}

func (m *CrawlerConf) GetRule() *CrawlerConf_Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

func (m *CrawlerConf) GetIsClosed() bool {
	if m != nil {
		return m.IsClosed
	}
	return false
}

func (m *CrawlerConf) GetNextAt() uint32 {
	if m != nil {
		return m.NextAt
	}
	return 0
}

func (m *CrawlerConf) GetInterval() uint32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *CrawlerConf) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

type CrawlerConf_Rule struct {
	UseProxy             bool     `protobuf:"varint,1,opt,name=use_proxy,json=useProxy" json:"use_proxy,omitempty"`
	Xpath                string   `protobuf:"bytes,2,opt,name=xpath" json:"xpath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" gorm:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" gorm:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" gorm:"-"`
}

func (m *CrawlerConf_Rule) Reset()         { *m = CrawlerConf_Rule{} }
func (m *CrawlerConf_Rule) String() string { return proto.CompactTextString(m) }
func (*CrawlerConf_Rule) ProtoMessage()    {}
func (*CrawlerConf_Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_subscription_af37a71ad6fa795b, []int{0, 0}
}
func (m *CrawlerConf_Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlerConf_Rule.Unmarshal(m, b)
}
func (m *CrawlerConf_Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlerConf_Rule.Marshal(b, m, deterministic)
}
func (dst *CrawlerConf_Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlerConf_Rule.Merge(dst, src)
}
func (m *CrawlerConf_Rule) XXX_Size() int {
	return xxx_messageInfo_CrawlerConf_Rule.Size(m)
}
func (m *CrawlerConf_Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlerConf_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlerConf_Rule proto.InternalMessageInfo

func (m *CrawlerConf_Rule) GetUseProxy() bool {
	if m != nil {
		return m.UseProxy
	}
	return false
}

func (m *CrawlerConf_Rule) GetXpath() string {
	if m != nil {
		return m.Xpath
	}
	return ""
}

type ProxyNode struct {
	Id        uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CreatedAt uint32 `protobuf:"varint,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt uint32 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	// HOST:PORT
	// @gorm: type:varchar(1000); unique_index: idx_proxy_node_url
	// @v: max=1000
	Url           string `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	ProxyNodeType uint32 `protobuf:"varint,5,opt,name=proxy_node_type,json=proxyNodeType" json:"proxy_node_type,omitempty"`
	// @gorm: type:text
	NodeDetail        *ProxyNode_NodeDetail `protobuf:"bytes,6,opt,name=node_detail,json=nodeDetail" json:"node_detail,omitempty"`
	ProxySpeed        float64               `protobuf:"fixed64,7,opt,name=proxy_speed,json=proxySpeed" json:"proxy_speed,omitempty"`
	ProxyNetworkDelay float64               `protobuf:"fixed64,8,opt,name=proxy_network_delay,json=proxyNetworkDelay" json:"proxy_network_delay,omitempty"`
	// @grom: index: idx_next_check_at
	NextCheckAt   uint32 `protobuf:"varint,9,opt,name=next_check_at,json=nextCheckAt" json:"next_check_at,omitempty"`
	CheckInterval uint32 `protobuf:"varint,10,opt,name=check_interval,json=checkInterval" json:"check_interval,omitempty"`
	CrawlId       uint64 `protobuf:"varint,11,opt,name=crawl_id,json=crawlId" json:"crawl_id,omitempty"`
	// @grom: index: idx_next_check_at
	DeathCount uint32 `protobuf:"varint,12,opt,name=death_count,json=deathCount" json:"death_count,omitempty"`
	// @grom: index: idx_next_check_at
	IsClose              bool     `protobuf:"varint,13,opt,name=is_close,json=isClose" json:"is_close,omitempty"`
	LastCrawlerAt        uint32   `protobuf:"varint,14,opt,name=last_crawler_at,json=lastCrawlerAt" json:"last_crawler_at,omitempty"`
	AvailableCount       uint64   `protobuf:"varint,15,opt,name=available_count,json=availableCount" json:"available_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" gorm:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" gorm:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" gorm:"-"`
}

func (m *ProxyNode) Reset()         { *m = ProxyNode{} }
func (m *ProxyNode) String() string { return proto.CompactTextString(m) }
func (*ProxyNode) ProtoMessage()    {}
func (*ProxyNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_subscription_af37a71ad6fa795b, []int{1}
}
func (m *ProxyNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyNode.Unmarshal(m, b)
}
func (m *ProxyNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyNode.Marshal(b, m, deterministic)
}
func (dst *ProxyNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyNode.Merge(dst, src)
}
func (m *ProxyNode) XXX_Size() int {
	return xxx_messageInfo_ProxyNode.Size(m)
}
func (m *ProxyNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyNode.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyNode proto.InternalMessageInfo

func (m *ProxyNode) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProxyNode) GetCreatedAt() uint32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ProxyNode) GetUpdatedAt() uint32 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *ProxyNode) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ProxyNode) GetProxyNodeType() uint32 {
	if m != nil {
		return m.ProxyNodeType
	}
	return 0
}

func (m *ProxyNode) GetNodeDetail() *ProxyNode_NodeDetail {
	if m != nil {
		return m.NodeDetail
	}
	return nil
}

func (m *ProxyNode) GetProxySpeed() float64 {
	if m != nil {
		return m.ProxySpeed
	}
	return 0
}

func (m *ProxyNode) GetProxyNetworkDelay() float64 {
	if m != nil {
		return m.ProxyNetworkDelay
	}
	return 0
}

func (m *ProxyNode) GetNextCheckAt() uint32 {
	if m != nil {
		return m.NextCheckAt
	}
	return 0
}

func (m *ProxyNode) GetCheckInterval() uint32 {
	if m != nil {
		return m.CheckInterval
	}
	return 0
}

func (m *ProxyNode) GetCrawlId() uint64 {
	if m != nil {
		return m.CrawlId
	}
	return 0
}

func (m *ProxyNode) GetDeathCount() uint32 {
	if m != nil {
		return m.DeathCount
	}
	return 0
}

func (m *ProxyNode) GetIsClose() bool {
	if m != nil {
		return m.IsClose
	}
	return false
}

func (m *ProxyNode) GetLastCrawlerAt() uint32 {
	if m != nil {
		return m.LastCrawlerAt
	}
	return 0
}

func (m *ProxyNode) GetAvailableCount() uint64 {
	if m != nil {
		return m.AvailableCount
	}
	return 0
}

type ProxyNode_NodeDetail struct {
	Buf                  string   `protobuf:"bytes,1,opt,name=buf" json:"buf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" gorm:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" gorm:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" gorm:"-"`
}

func (m *ProxyNode_NodeDetail) Reset()         { *m = ProxyNode_NodeDetail{} }
func (m *ProxyNode_NodeDetail) String() string { return proto.CompactTextString(m) }
func (*ProxyNode_NodeDetail) ProtoMessage()    {}
func (*ProxyNode_NodeDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_subscription_af37a71ad6fa795b, []int{1, 0}
}
func (m *ProxyNode_NodeDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyNode_NodeDetail.Unmarshal(m, b)
}
func (m *ProxyNode_NodeDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyNode_NodeDetail.Marshal(b, m, deterministic)
}
func (dst *ProxyNode_NodeDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyNode_NodeDetail.Merge(dst, src)
}
func (m *ProxyNode_NodeDetail) XXX_Size() int {
	return xxx_messageInfo_ProxyNode_NodeDetail.Size(m)
}
func (m *ProxyNode_NodeDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyNode_NodeDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyNode_NodeDetail proto.InternalMessageInfo

func (m *ProxyNode_NodeDetail) GetBuf() string {
	if m != nil {
		return m.Buf
	}
	return ""
}

func init() {
	proto.RegisterType((*CrawlerConf)(nil), "subscription.CrawlerConf")
	proto.RegisterType((*CrawlerConf_Rule)(nil), "subscription.CrawlerConf.Rule")
	proto.RegisterType((*ProxyNode)(nil), "subscription.ProxyNode")
	proto.RegisterType((*ProxyNode_NodeDetail)(nil), "subscription.ProxyNode.NodeDetail")
	proto.RegisterEnum("subscription.ErrCode", ErrCode_name, ErrCode_value)
	proto.RegisterEnum("subscription.CrawlType", CrawlType_name, CrawlType_value)
	proto.RegisterEnum("subscription.ProxyNodeType", ProxyNodeType_name, ProxyNodeType_value)
}

func init() { proto.RegisterFile("subscription.proto", fileDescriptor_subscription_af37a71ad6fa795b) }

var fileDescriptor_subscription_af37a71ad6fa795b = []byte{
	// 644 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0x93, 0xb4, 0xb1, 0xc7, 0x8d, 0x6b, 0xb6, 0xa5, 0x75, 0x83, 0x28, 0x51, 0x24, 0x20,
	0xea, 0x21, 0x87, 0x72, 0xe2, 0x18, 0x5c, 0x90, 0x7a, 0xa0, 0xaa, 0xdc, 0x82, 0x10, 0x17, 0x6b,
	0x63, 0x6f, 0x89, 0xe9, 0x62, 0x5b, 0xeb, 0x75, 0x9b, 0xf4, 0xdb, 0xf8, 0x24, 0x3e, 0x02, 0xcd,
	0xd8, 0x71, 0x63, 0x71, 0xe5, 0x12, 0xed, 0xbc, 0xb7, 0xbb, 0xf3, 0xf6, 0xcd, 0x8b, 0x81, 0x15,
	0xe5, 0xbc, 0x88, 0x54, 0x92, 0xeb, 0x24, 0x4b, 0xa7, 0xb9, 0xca, 0x74, 0xc6, 0x76, 0x37, 0xb1,
	0xf1, 0x9f, 0x0e, 0xd8, 0xbe, 0xe2, 0x0f, 0x52, 0x28, 0x3f, 0x4b, 0x6f, 0x99, 0x03, 0x9d, 0x24,
	0xf6, 0x8c, 0x91, 0x31, 0xe9, 0x05, 0x9d, 0x24, 0x66, 0x2f, 0x01, 0x22, 0x25, 0xb8, 0x16, 0x71,
	0xc8, 0xb5, 0xd7, 0x19, 0x19, 0x93, 0x41, 0x60, 0xd5, 0xc8, 0x4c, 0x23, 0x5d, 0xe6, 0xf1, 0x9a,
	0xee, 0x56, 0x74, 0x8d, 0xcc, 0x34, 0x7b, 0x01, 0x56, 0x84, 0x97, 0x87, 0xa5, 0x92, 0x5e, 0x6f,
	0x64, 0x4c, 0xac, 0xc0, 0x24, 0xe0, 0x8b, 0x92, 0xd5, 0xd5, 0x48, 0xea, 0x55, 0x2e, 0xbc, 0xed,
	0xf5, 0xd5, 0xfc, 0x41, 0xde, 0xac, 0x72, 0xc1, 0xce, 0xa0, 0xa7, 0x4a, 0x29, 0xbc, 0x9d, 0x91,
	0x31, 0xb1, 0xcf, 0x4e, 0xa6, 0xad, 0xa7, 0x6c, 0x48, 0x9e, 0x06, 0xa5, 0x14, 0x01, 0xed, 0xc5,
	0x7e, 0x49, 0x11, 0x46, 0x32, 0x2b, 0x44, 0xec, 0xf5, 0x47, 0xc6, 0xc4, 0x0c, 0xcc, 0xa4, 0xf0,
	0xa9, 0x66, 0x47, 0xd0, 0x4f, 0xc5, 0x52, 0xa3, 0x50, 0x93, 0x9a, 0xed, 0x60, 0x39, 0xd3, 0x6c,
	0x08, 0x66, 0x92, 0x6a, 0xa1, 0xee, 0xb9, 0xf4, 0x2c, 0x62, 0x9a, 0x9a, 0x31, 0xe8, 0xa5, 0x99,
	0x16, 0x1e, 0x90, 0x78, 0x5a, 0x0f, 0xdf, 0x43, 0x2f, 0xa8, 0xbb, 0x95, 0x85, 0x08, 0x73, 0x95,
	0x2d, 0x57, 0x64, 0x99, 0x19, 0x98, 0x65, 0x21, 0xae, 0xb0, 0x66, 0x07, 0xb0, 0xbd, 0xcc, 0xb9,
	0x5e, 0x90, 0x67, 0x56, 0x50, 0x15, 0xe3, 0xdf, 0x3d, 0xb0, 0x88, 0xbf, 0xcc, 0x62, 0xf1, 0x9f,
	0xcd, 0x76, 0xa1, 0xfb, 0x64, 0x33, 0x2e, 0xd9, 0x1b, 0xd8, 0x23, 0x71, 0x61, 0x9a, 0xc5, 0x62,
	0xd3, 0xe6, 0x41, 0xbe, 0xd6, 0x40, 0x56, 0xfb, 0x60, 0xd3, 0x8e, 0x58, 0x68, 0x9e, 0xc8, 0xda,
	0xf1, 0x71, 0xdb, 0xf1, 0x46, 0xf5, 0x14, 0x7f, 0xce, 0x69, 0x67, 0x00, 0x69, 0xb3, 0x66, 0xaf,
	0xc0, 0xae, 0x9a, 0x15, 0xb9, 0xa8, 0xdd, 0x37, 0x02, 0x20, 0xe8, 0x1a, 0x11, 0x36, 0x85, 0xfd,
	0x5a, 0x8d, 0xd0, 0x0f, 0x99, 0xba, 0x0b, 0x63, 0x21, 0xf9, 0x8a, 0x66, 0x61, 0x04, 0xcf, 0x2a,
	0x45, 0x15, 0x73, 0x8e, 0x04, 0x1b, 0xc3, 0x80, 0xe6, 0x15, 0x2d, 0x44, 0x74, 0x87, 0x2f, 0xae,
	0x66, 0x63, 0x23, 0xe8, 0x23, 0x36, 0xd3, 0xec, 0x35, 0x38, 0x15, 0xdd, 0x0c, 0x10, 0xaa, 0x07,
	0x12, 0x7a, 0xb1, 0x9e, 0xe2, 0x31, 0x54, 0xb1, 0x0b, 0x93, 0xd8, 0xb3, 0xc9, 0xee, 0x3e, 0xd5,
	0x17, 0x31, 0xca, 0x8e, 0x05, 0xd7, 0x8b, 0x30, 0xca, 0xca, 0x54, 0x7b, 0xbb, 0x74, 0x1c, 0x08,
	0xf2, 0x11, 0xc1, 0xb3, 0xeb, 0x4c, 0x79, 0x03, 0x1a, 0x72, 0xbf, 0x8e, 0x14, 0xfa, 0x2b, 0x79,
	0xa1, 0xc3, 0xa8, 0x4a, 0x23, 0x6a, 0x74, 0xaa, 0xf6, 0x08, 0xd7, 0x19, 0x9d, 0x69, 0xf6, 0x16,
	0xf6, 0xf8, 0x3d, 0x4f, 0x24, 0x9f, 0x4b, 0x51, 0xf7, 0xd9, 0x23, 0x15, 0x4e, 0x03, 0x53, 0xaf,
	0xe1, 0x09, 0xc0, 0x93, 0xbb, 0x38, 0xd0, 0x79, 0x79, 0x4b, 0xf9, 0xb0, 0x02, 0x5c, 0x9e, 0x1e,
	0x42, 0xff, 0xa3, 0x52, 0x3e, 0x66, 0xc7, 0x86, 0xfe, 0x75, 0x19, 0x45, 0xa2, 0x28, 0xdc, 0xad,
	0xd3, 0x05, 0x58, 0x7e, 0xf3, 0xc7, 0x71, 0x61, 0xb7, 0x29, 0x2e, 0x13, 0xe9, 0x6e, 0xb1, 0x63,
	0x78, 0xde, 0x20, 0xd7, 0x1b, 0x43, 0x75, 0x0d, 0xc6, 0xc0, 0x69, 0xa8, 0x6f, 0x18, 0x51, 0xb7,
	0xc3, 0x86, 0x70, 0xd8, 0x60, 0x9f, 0xca, 0xc7, 0xc7, 0xd5, 0x67, 0xae, 0xa3, 0x45, 0x92, 0xfe,
	0x70, 0xbb, 0xa7, 0x29, 0x0c, 0xae, 0x5a, 0xd9, 0x39, 0x00, 0xb7, 0x05, 0x54, 0x1d, 0x0f, 0x81,
	0xb5, 0xd0, 0xaf, 0xbf, 0x50, 0xa8, 0xc1, 0x8e, 0x60, 0xbf, 0x85, 0xdf, 0xa8, 0xec, 0x27, 0x4f,
	0xdd, 0xce, 0xbf, 0x07, 0x24, 0x1e, 0xe8, 0x9e, 0x39, 0xd0, 0xfa, 0x5e, 0x7d, 0x70, 0xbe, 0xb7,
	0xea, 0xf9, 0x0e, 0x7d, 0xd4, 0xde, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x15, 0x60, 0x33, 0xc3,
	0xea, 0x04, 0x00, 0x00,
}
