package country

//go:generate pie CountryList.*
type CountryList []*CountryInfo

var countryList = CountryList{
	{
		Code:    "AD",
		Unicode: "U+1F1E6U+1F1E9",
		EnName:  "Andorra",
		Emoji:   "🇦🇩",
		CnName:  "安道尔共和国",
	},
	{
		Code:    "AE",
		Unicode: "U+1F1E6U+1F1EA",
		EnName:  "UnitedArabEmirates",
		Emoji:   "🇦🇪",
		CnName:  "阿拉伯联合酋长国",
	},
	{
		Code:    "AF",
		Unicode: "U+1F1E6U+1F1EB",
		EnName:  "Afghanistan",
		Emoji:   "🇦🇫",
		CnName:  "阿富汗",
	},
	{
		Code:    "AG",
		Unicode: "U+1F1E6U+1F1EC",
		EnName:  "Antigua&Barbuda",
		Emoji:   "🇦🇬",
		CnName:  "安提瓜和巴布达",
	},
	{
		Code:    "AI",
		Unicode: "U+1F1E6U+1F1EE",
		EnName:  "Anguilla",
		Emoji:   "🇦🇮",
		CnName:  "安圭拉岛",
	},
	{
		Code:    "AL",
		Unicode: "U+1F1E6U+1F1F1",
		EnName:  "Albania",
		Emoji:   "🇦🇱",
		CnName:  "阿尔巴尼亚",
	},
	{
		Code:    "AM",
		Unicode: "U+1F1E6U+1F1F2",
		EnName:  "Armenia",
		Emoji:   "🇦🇲",
		CnName:  "亚美尼亚",
	},
	{
		Code:    "AO",
		Unicode: "U+1F1E6U+1F1F4",
		EnName:  "Angola",
		Emoji:   "🇦🇴",
		CnName:  "安哥拉",
	},
	{
		Code:    "AR",
		Unicode: "U+1F1E6U+1F1F7",
		EnName:  "Argentina",
		Emoji:   "🇦🇷",
		CnName:  "阿根廷",
	},
	{
		Code:    "AT",
		Unicode: "U+1F1E6U+1F1F9",
		EnName:  "Austria",
		Emoji:   "🇦🇹",
		CnName:  "奥地利",
	},
	{
		Code:    "AU",
		Unicode: "U+1F1E6U+1F1FA",
		EnName:  "Australia",
		Emoji:   "🇦🇺",
		CnName:  "澳大利亚",
	},
	{
		Code:    "AZ",
		Unicode: "U+1F1E6U+1F1FF",
		EnName:  "Azerbaijan",
		Emoji:   "🇦🇿",
		CnName:  "阿塞拜疆",
	},
	{
		Code:    "BB",
		Unicode: "U+1F1E7U+1F1E7",
		EnName:  "Barbados",
		Emoji:   "🇧🇧",
		CnName:  "巴巴多斯",
	},
	{
		Code:    "BD",
		Unicode: "U+1F1E7U+1F1E9",
		EnName:  "Bangladesh",
		Emoji:   "🇧🇩",
		CnName:  "孟加拉国",
	},
	{
		Code:    "BE",
		Unicode: "U+1F1E7U+1F1EA",
		EnName:  "Belgium",
		Emoji:   "🇧🇪",
		CnName:  "比利时",
	},
	{
		Code:    "BF",
		Unicode: "U+1F1E7U+1F1EB",
		EnName:  "BurkinaFaso",
		Emoji:   "🇧🇫",
		CnName:  "布基纳法索",
	},
	{
		Code:    "BG",
		Unicode: "U+1F1E7U+1F1EC",
		EnName:  "Bulgaria",
		Emoji:   "🇧🇬",
		CnName:  "保加利亚",
	},
	{
		Code:    "BH",
		Unicode: "U+1F1E7U+1F1ED",
		EnName:  "Bahrain",
		Emoji:   "🇧🇭",
		CnName:  "巴林",
	},
	{
		Code:    "BI",
		Unicode: "U+1F1E7U+1F1EE",
		EnName:  "Burundi",
		Emoji:   "🇧🇮",
		CnName:  "布隆迪",
	},
	{
		Code:    "BJ",
		Unicode: "U+1F1E7U+1F1EF",
		EnName:  "Benin",
		Emoji:   "🇧🇯",
		CnName:  "贝宁",
	},
	{
		Code:    "BM",
		Unicode: "U+1F1E7U+1F1F2",
		EnName:  "Bermuda",
		Emoji:   "🇧🇲",
		CnName:  "百慕大群岛",
	},
	{
		Code:    "BN",
		Unicode: "U+1F1E7U+1F1F3",
		EnName:  "Brunei",
		Emoji:   "🇧🇳",
		CnName:  "文莱",
	},
	{
		Code:    "BO",
		Unicode: "U+1F1E7U+1F1F4",
		EnName:  "Bolivia",
		Emoji:   "🇧🇴",
		CnName:  "玻利维亚",
	},
	{
		Code:    "BR",
		Unicode: "U+1F1E7U+1F1F7",
		EnName:  "Brazil",
		Emoji:   "🇧🇷",
		CnName:  "巴西",
	},
	{
		Code:    "BS",
		Unicode: "U+1F1E7U+1F1F8",
		EnName:  "Bahamas",
		Emoji:   "🇧🇸",
		CnName:  "巴哈马",
	},
	{
		Code:    "BW",
		Unicode: "U+1F1E7U+1F1FC",
		EnName:  "Botswana",
		Emoji:   "🇧🇼",
		CnName:  "博茨瓦纳",
	},
	{
		Code:    "BY",
		Unicode: "U+1F1E7U+1F1FE",
		EnName:  "Belarus",
		Emoji:   "🇧🇾",
		CnName:  "白俄罗斯",
	},
	{
		Code:    "BZ",
		Unicode: "U+1F1E7U+1F1FF",
		EnName:  "Belize",
		Emoji:   "🇧🇿",
		CnName:  "伯利兹",
	},
	{
		Code:    "CA",
		Unicode: "U+1F1E8U+1F1E6",
		EnName:  "Canada",
		Emoji:   "🇨🇦",
		CnName:  "加拿大",
	},
	{
		Code:    "CF",
		Unicode: "U+1F1E8U+1F1EB",
		EnName:  "CentralAfricanRepublic",
		Emoji:   "🇨🇫",
		CnName:  "中非共和国",
	},
	{
		Code:    "CG",
		Unicode: "U+1F1E8U+1F1EC",
		EnName:  "Congo-Brazzaville",
		Emoji:   "🇨🇬",
		CnName:  "刚果",
	},
	{
		Code:    "CH",
		Unicode: "U+1F1E8U+1F1ED",
		EnName:  "Switzerland",
		Emoji:   "🇨🇭",
		CnName:  "瑞士",
	},
	{
		Code:    "CK",
		Unicode: "U+1F1E8U+1F1F0",
		EnName:  "CookIslands",
		Emoji:   "🇨🇰",
		CnName:  "库克群岛",
	},
	{
		Code:    "CL",
		Unicode: "U+1F1E8U+1F1F1",
		EnName:  "Chile",
		Emoji:   "🇨🇱",
		CnName:  "智利",
	},
	{
		Code:    "CM",
		Unicode: "U+1F1E8U+1F1F2",
		EnName:  "Cameroon",
		Emoji:   "🇨🇲",
		CnName:  "喀麦隆",
	},
	{
		Code:    "CN",
		Unicode: "U+1F1E8U+1F1F3",
		EnName:  "China",
		Emoji:   "🇨🇳",
		CnName:  "中国",
	},
	{
		Code:    "CO",
		Unicode: "U+1F1E8U+1F1F4",
		EnName:  "Colombia",
		Emoji:   "🇨🇴",
		CnName:  "哥伦比亚",
	},
	{
		Code:    "CR",
		Unicode: "U+1F1E8U+1F1F7",
		EnName:  "CostaRica",
		Emoji:   "🇨🇷",
		CnName:  "哥斯达黎加",
	},
	{
		Code:    "CU",
		Unicode: "U+1F1E8U+1F1FA",
		EnName:  "Cuba",
		Emoji:   "🇨🇺",
		CnName:  "古巴",
	},
	{
		Code:    "CY",
		Unicode: "U+1F1E8U+1F1FE",
		EnName:  "Cyprus",
		Emoji:   "🇨🇾",
		CnName:  "塞浦路斯",
	},
	{
		Code:    "CZ",
		Unicode: "U+1F1E8U+1F1FF",
		EnName:  "Czechia",
		Emoji:   "🇨🇿",
		CnName:  "捷克",
	},
	{
		Code:    "DE",
		Unicode: "U+1F1E9U+1F1EA",
		EnName:  "Germany",
		Emoji:   "🇩🇪",
		CnName:  "德国",
	},
	{
		Code:    "DJ",
		Unicode: "U+1F1E9U+1F1EF",
		EnName:  "Djibouti",
		Emoji:   "🇩🇯",
		CnName:  "吉布提",
	},
	{
		Code:    "DK",
		Unicode: "U+1F1E9U+1F1F0",
		EnName:  "Denmark",
		Emoji:   "🇩🇰",
		CnName:  "丹麦",
	},
	{
		Code:    "DO",
		Unicode: "U+1F1E9U+1F1F4",
		EnName:  "DominicanRepublic",
		Emoji:   "🇩🇴",
		CnName:  "多米尼加共和国",
	},
	{
		Code:    "DZ",
		Unicode: "U+1F1E9U+1F1FF",
		EnName:  "Algeria",
		Emoji:   "🇩🇿",
		CnName:  "阿尔及利亚",
	},
	{
		Code:    "EC",
		Unicode: "U+1F1EAU+1F1E8",
		EnName:  "Ecuador",
		Emoji:   "🇪🇨",
		CnName:  "厄瓜多尔",
	},
	{
		Code:    "EE",
		Unicode: "U+1F1EAU+1F1EA",
		EnName:  "Estonia",
		Emoji:   "🇪🇪",
		CnName:  "爱沙尼亚",
	},
	{
		Code:    "EG",
		Unicode: "U+1F1EAU+1F1EC",
		EnName:  "Egypt",
		Emoji:   "🇪🇬",
		CnName:  "埃及",
	},
	{
		Code:    "ES",
		Unicode: "U+1F1EAU+1F1F8",
		EnName:  "Spain",
		Emoji:   "🇪🇸",
		CnName:  "西班牙",
	},
	{
		Code:    "ET",
		Unicode: "U+1F1EAU+1F1F9",
		EnName:  "Ethiopia",
		Emoji:   "🇪🇹",
		CnName:  "埃塞俄比亚",
	},
	{
		Code:    "FI",
		Unicode: "U+1F1EBU+1F1EE",
		EnName:  "Finland",
		Emoji:   "🇫🇮",
		CnName:  "芬兰",
	},
	{
		Code:    "FJ",
		Unicode: "U+1F1EBU+1F1EF",
		EnName:  "Fiji",
		Emoji:   "🇫🇯",
		CnName:  "斐济",
	},
	{
		Code:    "FR",
		Unicode: "U+1F1EBU+1F1F7",
		EnName:  "France",
		Emoji:   "🇫🇷",
		CnName:  "法国",
	},
	{
		Code:    "GA",
		Unicode: "U+1F1ECU+1F1E6",
		EnName:  "Gabon",
		Emoji:   "🇬🇦",
		CnName:  "加蓬",
	},
	{
		Code:    "GB",
		Unicode: "U+1F1ECU+1F1E7",
		EnName:  "UnitedKingdom",
		Emoji:   "🇬🇧",
		CnName:  "英国",
	},
	{
		Code:    "GD",
		Unicode: "U+1F1ECU+1F1E9",
		EnName:  "Grenada",
		Emoji:   "🇬🇩",
		CnName:  "格林纳达",
	},
	{
		Code:    "GE",
		Unicode: "U+1F1ECU+1F1EA",
		EnName:  "Georgia",
		Emoji:   "🇬🇪",
		CnName:  "格鲁吉亚",
	},
	{
		Code:    "GF",
		Unicode: "U+1F1ECU+1F1EB",
		EnName:  "FrenchGuiana",
		Emoji:   "🇬🇫",
		CnName:  "法属圭亚那",
	},
	{
		Code:    "GH",
		Unicode: "U+1F1ECU+1F1ED",
		EnName:  "Ghana",
		Emoji:   "🇬🇭",
		CnName:  "加纳",
	},
	{
		Code:    "GI",
		Unicode: "U+1F1ECU+1F1EE",
		EnName:  "Gibraltar",
		Emoji:   "🇬🇮",
		CnName:  "直布罗陀",
	},
	{
		Code:    "GM",
		Unicode: "U+1F1ECU+1F1F2",
		EnName:  "Gambia",
		Emoji:   "🇬🇲",
		CnName:  "冈比亚",
	},
	{
		Code:    "GN",
		Unicode: "U+1F1ECU+1F1F3",
		EnName:  "Guinea",
		Emoji:   "🇬🇳",
		CnName:  "几内亚",
	},
	{
		Code:    "GR",
		Unicode: "U+1F1ECU+1F1F7",
		EnName:  "Greece",
		Emoji:   "🇬🇷",
		CnName:  "希腊",
	},
	{
		Code:    "GT",
		Unicode: "U+1F1ECU+1F1F9",
		EnName:  "Guatemala",
		Emoji:   "🇬🇹",
		CnName:  "危地马拉",
	},
	{
		Code:    "GU",
		Unicode: "U+1F1ECU+1F1FA",
		EnName:  "Guam",
		Emoji:   "🇬🇺",
		CnName:  "关岛",
	},
	{
		Code:    "GY",
		Unicode: "U+1F1ECU+1F1FE",
		EnName:  "Guyana",
		Emoji:   "🇬🇾",
		CnName:  "圭亚那",
	},
	{
		Code:    "HK",
		Unicode: "U+1F1EDU+1F1F0",
		EnName:  "HongKongSARChina",
		Emoji:   "🇭🇰",
		CnName:  "香港",
	},
	{
		Code:    "HN",
		Unicode: "U+1F1EDU+1F1F3",
		EnName:  "Honduras",
		Emoji:   "🇭🇳",
		CnName:  "洪都拉斯",
	},
	{
		Code:    "HT",
		Unicode: "U+1F1EDU+1F1F9",
		EnName:  "Haiti",
		Emoji:   "🇭🇹",
		CnName:  "海地",
	},
	{
		Code:    "HU",
		Unicode: "U+1F1EDU+1F1FA",
		EnName:  "Hungary",
		Emoji:   "🇭🇺",
		CnName:  "匈牙利",
	},
	{
		Code:    "ID",
		Unicode: "U+1F1EEU+1F1E9",
		EnName:  "Indonesia",
		Emoji:   "🇮🇩",
		CnName:  "印度尼西亚",
	},
	{
		Code:    "IE",
		Unicode: "U+1F1EEU+1F1EA",
		EnName:  "Ireland",
		Emoji:   "🇮🇪",
		CnName:  "爱尔兰",
	},
	{
		Code:    "IL",
		Unicode: "U+1F1EEU+1F1F1",
		EnName:  "Israel",
		Emoji:   "🇮🇱",
		CnName:  "以色列",
	},
	{
		Code:    "IN",
		Unicode: "U+1F1EEU+1F1F3",
		EnName:  "India",
		Emoji:   "🇮🇳",
		CnName:  "印度",
	},
	{
		Code:    "IQ",
		Unicode: "U+1F1EEU+1F1F6",
		EnName:  "Iraq",
		Emoji:   "🇮🇶",
		CnName:  "伊拉克",
	},
	{
		Code:    "IR",
		Unicode: "U+1F1EEU+1F1F7",
		EnName:  "Iran",
		Emoji:   "🇮🇷",
		CnName:  "伊朗",
	},
	{
		Code:    "IS",
		Unicode: "U+1F1EEU+1F1F8",
		EnName:  "Iceland",
		Emoji:   "🇮🇸",
		CnName:  "冰岛",
	},
	{
		Code:    "IT",
		Unicode: "U+1F1EEU+1F1F9",
		EnName:  "Italy",
		Emoji:   "🇮🇹",
		CnName:  "意大利",
	},
	{
		Code:    "JM",
		Unicode: "U+1F1EFU+1F1F2",
		EnName:  "Jamaica",
		Emoji:   "🇯🇲",
		CnName:  "牙买加",
	},
	{
		Code:    "JO",
		Unicode: "U+1F1EFU+1F1F4",
		EnName:  "Jordan",
		Emoji:   "🇯🇴",
		CnName:  "约旦",
	},
	{
		Code:    "JP",
		Unicode: "U+1F1EFU+1F1F5",
		EnName:  "Japan",
		Emoji:   "🇯🇵",
		CnName:  "日本",
	},
	{
		Code:    "KE",
		Unicode: "U+1F1F0U+1F1EA",
		EnName:  "Kenya",
		Emoji:   "🇰🇪",
		CnName:  "肯尼亚",
	},
	{
		Code:    "KG",
		Unicode: "U+1F1F0U+1F1EC",
		EnName:  "Kyrgyzstan",
		Emoji:   "🇰🇬",
		CnName:  "吉尔吉斯坦",
	},
	{
		Code:    "KH",
		Unicode: "U+1F1F0U+1F1ED",
		EnName:  "Cambodia",
		Emoji:   "🇰🇭",
		CnName:  "柬埔寨",
	},
	{
		Code:    "KP",
		Unicode: "U+1F1F0U+1F1F5",
		EnName:  "NorthKorea",
		Emoji:   "🇰🇵",
		CnName:  "朝鲜",
	},
	{
		Code:    "KR",
		Unicode: "U+1F1F0U+1F1F7",
		EnName:  "SouthKorea",
		Emoji:   "🇰🇷",
		CnName:  "韩国",
	},
	{
		Code:    "KW",
		Unicode: "U+1F1F0U+1F1FC",
		EnName:  "Kuwait",
		Emoji:   "🇰🇼",
		CnName:  "科威特",
	},
	{
		Code:    "KZ",
		Unicode: "U+1F1F0U+1F1FF",
		EnName:  "Kazakhstan",
		Emoji:   "🇰🇿",
		CnName:  "哈萨克斯坦",
	},
	{
		Code:    "LA",
		Unicode: "U+1F1F1U+1F1E6",
		EnName:  "Laos",
		Emoji:   "🇱🇦",
		CnName:  "老挝",
	},
	{
		Code:    "LB",
		Unicode: "U+1F1F1U+1F1E7",
		EnName:  "Lebanon",
		Emoji:   "🇱🇧",
		CnName:  "黎巴嫩",
	},
	{
		Code:    "LC",
		Unicode: "U+1F1F1U+1F1E8",
		EnName:  "St.Lucia",
		Emoji:   "🇱🇨",
		CnName:  "圣卢西亚",
	},
	{
		Code:    "LI",
		Unicode: "U+1F1F1U+1F1EE",
		EnName:  "Liechtenstein",
		Emoji:   "🇱🇮",
		CnName:  "列支敦士登",
	},
	{
		Code:    "LK",
		Unicode: "U+1F1F1U+1F1F0",
		EnName:  "SriLanka",
		Emoji:   "🇱🇰",
		CnName:  "斯里兰卡",
	},
	{
		Code:    "LR",
		Unicode: "U+1F1F1U+1F1F7",
		EnName:  "Liberia",
		Emoji:   "🇱🇷",
		CnName:  "利比里亚",
	},
	{
		Code:    "LS",
		Unicode: "U+1F1F1U+1F1F8",
		EnName:  "Lesotho",
		Emoji:   "🇱🇸",
		CnName:  "莱索托",
	},
	{
		Code:    "LT",
		Unicode: "U+1F1F1U+1F1F9",
		EnName:  "Lithuania",
		Emoji:   "🇱🇹",
		CnName:  "立陶宛",
	},
	{
		Code:    "LU",
		Unicode: "U+1F1F1U+1F1FA",
		EnName:  "Luxembourg",
		Emoji:   "🇱🇺",
		CnName:  "卢森堡",
	},
	{
		Code:    "LV",
		Unicode: "U+1F1F1U+1F1FB",
		EnName:  "Latvia",
		Emoji:   "🇱🇻",
		CnName:  "拉脱维亚",
	},
	{
		Code:    "LY",
		Unicode: "U+1F1F1U+1F1FE",
		EnName:  "Libya",
		Emoji:   "🇱🇾",
		CnName:  "利比亚",
	},
	{
		Code:    "MA",
		Unicode: "U+1F1F2U+1F1E6",
		EnName:  "Morocco",
		Emoji:   "🇲🇦",
		CnName:  "摩洛哥",
	},
	{
		Code:    "MC",
		Unicode: "U+1F1F2U+1F1E8",
		EnName:  "Monaco",
		Emoji:   "🇲🇨",
		CnName:  "摩纳哥",
	},
	{
		Code:    "MD",
		Unicode: "U+1F1F2U+1F1E9",
		EnName:  "Moldova",
		Emoji:   "🇲🇩",
		CnName:  "摩尔多瓦",
	},
	{
		Code:    "MG",
		Unicode: "U+1F1F2U+1F1EC",
		EnName:  "Madagascar",
		Emoji:   "🇲🇬",
		CnName:  "马达加斯加",
	},
	{
		Code:    "ML",
		Unicode: "U+1F1F2U+1F1F1",
		EnName:  "Mali",
		Emoji:   "🇲🇱",
		CnName:  "马里",
	},
	{
		Code:    "MM",
		Unicode: "U+1F1F2U+1F1F2",
		EnName:  "Myanmar(Burma)",
		Emoji:   "🇲🇲",
		CnName:  "缅甸",
	},
	{
		Code:    "MN",
		Unicode: "U+1F1F2U+1F1F3",
		EnName:  "Mongolia",
		Emoji:   "🇲🇳",
		CnName:  "蒙古",
	},
	{
		Code:    "MO",
		Unicode: "U+1F1F2U+1F1F4",
		EnName:  "MacauSARChina",
		Emoji:   "🇲🇴",
		CnName:  "澳门",
	},
	{
		Code:    "MS",
		Unicode: "U+1F1F2U+1F1F8",
		EnName:  "Montserrat",
		Emoji:   "🇲🇸",
		CnName:  "蒙特塞拉特岛",
	},
	{
		Code:    "MT",
		Unicode: "U+1F1F2U+1F1F9",
		EnName:  "Malta",
		Emoji:   "🇲🇹",
		CnName:  "马耳他",
	},
	{
		Code:    "MU",
		Unicode: "U+1F1F2U+1F1FA",
		EnName:  "Mauritius",
		Emoji:   "🇲🇺",
		CnName:  "毛里求斯",
	},
	{
		Code:    "MV",
		Unicode: "U+1F1F2U+1F1FB",
		EnName:  "Maldives",
		Emoji:   "🇲🇻",
		CnName:  "马尔代夫",
	},
	{
		Code:    "MW",
		Unicode: "U+1F1F2U+1F1FC",
		EnName:  "Malawi",
		Emoji:   "🇲🇼",
		CnName:  "马拉维",
	},
	{
		Code:    "MX",
		Unicode: "U+1F1F2U+1F1FD",
		EnName:  "Mexico",
		Emoji:   "🇲🇽",
		CnName:  "墨西哥",
	},
	{
		Code:    "MY",
		Unicode: "U+1F1F2U+1F1FE",
		EnName:  "Malaysia",
		Emoji:   "🇲🇾",
		CnName:  "马来西亚",
	},
	{
		Code:    "MZ",
		Unicode: "U+1F1F2U+1F1FF",
		EnName:  "Mozambique",
		Emoji:   "🇲🇿",
		CnName:  "莫桑比克",
	},
	{
		Code:    "NA",
		Unicode: "U+1F1F3U+1F1E6",
		EnName:  "Namibia",
		Emoji:   "🇳🇦",
		CnName:  "纳米比亚",
	},
	{
		Code:    "NE",
		Unicode: "U+1F1F3U+1F1EA",
		EnName:  "Niger",
		Emoji:   "🇳🇪",
		CnName:  "尼日尔",
	},
	{
		Code:    "NG",
		Unicode: "U+1F1F3U+1F1EC",
		EnName:  "Nigeria",
		Emoji:   "🇳🇬",
		CnName:  "尼日利亚",
	},
	{
		Code:    "NI",
		Unicode: "U+1F1F3U+1F1EE",
		EnName:  "Nicaragua",
		Emoji:   "🇳🇮",
		CnName:  "尼加拉瓜",
	},
	{
		Code:    "NL",
		Unicode: "U+1F1F3U+1F1F1",
		EnName:  "Netherlands",
		Emoji:   "🇳🇱",
		CnName:  "荷兰",
	},
	{
		Code:    "NO",
		Unicode: "U+1F1F3U+1F1F4",
		EnName:  "Norway",
		Emoji:   "🇳🇴",
		CnName:  "挪威",
	},
	{
		Code:    "NP",
		Unicode: "U+1F1F3U+1F1F5",
		EnName:  "Nepal",
		Emoji:   "🇳🇵",
		CnName:  "尼泊尔",
	},
	{
		Code:    "NR",
		Unicode: "U+1F1F3U+1F1F7",
		EnName:  "Nauru",
		Emoji:   "🇳🇷",
		CnName:  "瑙鲁",
	},
	{
		Code:    "NZ",
		Unicode: "U+1F1F3U+1F1FF",
		EnName:  "NewZealand",
		Emoji:   "🇳🇿",
		CnName:  "新西兰",
	},
	{
		Code:    "OM",
		Unicode: "U+1F1F4U+1F1F2",
		EnName:  "Oman",
		Emoji:   "🇴🇲",
		CnName:  "阿曼",
	},
	{
		Code:    "PA",
		Unicode: "U+1F1F5U+1F1E6",
		EnName:  "Panama",
		Emoji:   "🇵🇦",
		CnName:  "巴拿马",
	},
	{
		Code:    "PE",
		Unicode: "U+1F1F5U+1F1EA",
		EnName:  "Peru",
		Emoji:   "🇵🇪",
		CnName:  "秘鲁",
	},
	{
		Code:    "PF",
		Unicode: "U+1F1F5U+1F1EB",
		EnName:  "FrenchPolynesia",
		Emoji:   "🇵🇫",
		CnName:  "法属玻利尼西亚",
	},
	{
		Code:    "PG",
		Unicode: "U+1F1F5U+1F1EC",
		EnName:  "PapuaNewGuinea",
		Emoji:   "🇵🇬",
		CnName:  "巴布亚新几内亚",
	},
	{
		Code:    "PH",
		Unicode: "U+1F1F5U+1F1ED",
		EnName:  "Philippines",
		Emoji:   "🇵🇭",
		CnName:  "菲律宾",
	},
	{
		Code:    "PK",
		Unicode: "U+1F1F5U+1F1F0",
		EnName:  "Pakistan",
		Emoji:   "🇵🇰",
		CnName:  "巴基斯坦",
	},
	{
		Code:    "PL",
		Unicode: "U+1F1F5U+1F1F1",
		EnName:  "Poland",
		Emoji:   "🇵🇱",
		CnName:  "波兰",
	},
	{
		Code:    "PR",
		Unicode: "U+1F1F5U+1F1F7",
		EnName:  "PuertoRico",
		Emoji:   "🇵🇷",
		CnName:  "波多黎各",
	},
	{
		Code:    "PT",
		Unicode: "U+1F1F5U+1F1F9",
		EnName:  "Portugal",
		Emoji:   "🇵🇹",
		CnName:  "葡萄牙",
	},
	{
		Code:    "PY",
		Unicode: "U+1F1F5U+1F1FE",
		EnName:  "Paraguay",
		Emoji:   "🇵🇾",
		CnName:  "巴拉圭",
	},
	{
		Code:    "QA",
		Unicode: "U+1F1F6U+1F1E6",
		EnName:  "Qatar",
		Emoji:   "🇶🇦",
		CnName:  "卡塔尔",
	},
	{
		Code:    "RO",
		Unicode: "U+1F1F7U+1F1F4",
		EnName:  "Romania",
		Emoji:   "🇷🇴",
		CnName:  "罗马尼亚",
	},
	{
		Code:    "RU",
		Unicode: "U+1F1F7U+1F1FA",
		EnName:  "Russia",
		Emoji:   "🇷🇺",
		CnName:  "俄罗斯",
	},
	{
		Code:    "SA",
		Unicode: "U+1F1F8U+1F1E6",
		EnName:  "SaudiArabia",
		Emoji:   "🇸🇦",
		CnName:  "沙特阿拉伯",
	},
	{
		Code:    "SB",
		Unicode: "U+1F1F8U+1F1E7",
		EnName:  "SolomonIslands",
		Emoji:   "🇸🇧",
		CnName:  "所罗门群岛",
	},
	{
		Code:    "SC",
		Unicode: "U+1F1F8U+1F1E8",
		EnName:  "Seychelles",
		Emoji:   "🇸🇨",
		CnName:  "塞舌尔",
	},
	{
		Code:    "SD",
		Unicode: "U+1F1F8U+1F1E9",
		EnName:  "Sudan",
		Emoji:   "🇸🇩",
		CnName:  "苏丹",
	},
	{
		Code:    "SE",
		Unicode: "U+1F1F8U+1F1EA",
		EnName:  "Sweden",
		Emoji:   "🇸🇪",
		CnName:  "瑞典",
	},
	{
		Code:    "SG",
		Unicode: "U+1F1F8U+1F1EC",
		EnName:  "Singapore",
		Emoji:   "🇸🇬",
		CnName:  "新加坡",
	},
	{
		Code:    "SI",
		Unicode: "U+1F1F8U+1F1EE",
		EnName:  "Slovenia",
		Emoji:   "🇸🇮",
		CnName:  "斯洛文尼亚",
	},
	{
		Code:    "SK",
		Unicode: "U+1F1F8U+1F1F0",
		EnName:  "Slovakia",
		Emoji:   "🇸🇰",
		CnName:  "斯洛伐克",
	},
	{
		Code:    "SL",
		Unicode: "U+1F1F8U+1F1F1",
		EnName:  "SierraLeone",
		Emoji:   "🇸🇱",
		CnName:  "塞拉利昂",
	},
	{
		Code:    "SM",
		Unicode: "U+1F1F8U+1F1F2",
		EnName:  "SanMarino",
		Emoji:   "🇸🇲",
		CnName:  "圣马力诺",
	},
	{
		Code:    "SN",
		Unicode: "U+1F1F8U+1F1F3",
		EnName:  "Senegal",
		Emoji:   "🇸🇳",
		CnName:  "塞内加尔",
	},
	{
		Code:    "SO",
		Unicode: "U+1F1F8U+1F1F4",
		EnName:  "Somalia",
		Emoji:   "🇸🇴",
		CnName:  "索马里",
	},
	{
		Code:    "SR",
		Unicode: "U+1F1F8U+1F1F7",
		EnName:  "Suriname",
		Emoji:   "🇸🇷",
		CnName:  "苏里南",
	},
	{
		Code:    "ST",
		Unicode: "U+1F1F8U+1F1F9",
		EnName:  "SãoTomé&Príncipe",
		Emoji:   "🇸🇹",
		CnName:  "圣多美和普林西比",
	},
	{
		Code:    "SV",
		Unicode: "U+1F1F8U+1F1FB",
		EnName:  "ElSalvador",
		Emoji:   "🇸🇻",
		CnName:  "萨尔瓦多",
	},
	{
		Code:    "SY",
		Unicode: "U+1F1F8U+1F1FE",
		EnName:  "Syria",
		Emoji:   "🇸🇾",
		CnName:  "叙利亚",
	},
	{
		Code:    "SZ",
		Unicode: "U+1F1F8U+1F1FF",
		EnName:  "Swaziland",
		Emoji:   "🇸🇿",
		CnName:  "斯威士兰",
	},
	{
		Code:    "TD",
		Unicode: "U+1F1F9U+1F1E9",
		EnName:  "Chad",
		Emoji:   "🇹🇩",
		CnName:  "乍得",
	},
	{
		Code:    "TG",
		Unicode: "U+1F1F9U+1F1EC",
		EnName:  "Togo",
		Emoji:   "🇹🇬",
		CnName:  "多哥",
	},
	{
		Code:    "TH",
		Unicode: "U+1F1F9U+1F1ED",
		EnName:  "Thailand",
		Emoji:   "🇹🇭",
		CnName:  "泰国",
	},
	{
		Code:    "TJ",
		Unicode: "U+1F1F9U+1F1EF",
		EnName:  "Tajikistan",
		Emoji:   "🇹🇯",
		CnName:  "塔吉克斯坦",
	},
	{
		Code:    "TM",
		Unicode: "U+1F1F9U+1F1F2",
		EnName:  "Turkmenistan",
		Emoji:   "🇹🇲",
		CnName:  "土库曼斯坦",
	},
	{
		Code:    "TN",
		Unicode: "U+1F1F9U+1F1F3",
		EnName:  "Tunisia",
		Emoji:   "🇹🇳",
		CnName:  "突尼斯",
	},
	{
		Code:    "TO",
		Unicode: "U+1F1F9U+1F1F4",
		EnName:  "Tonga",
		Emoji:   "🇹🇴",
		CnName:  "汤加",
	},
	{
		Code:    "TR",
		Unicode: "U+1F1F9U+1F1F7",
		EnName:  "Turkey",
		Emoji:   "🇹🇷",
		CnName:  "土耳其",
	},
	{
		Code:    "TT",
		Unicode: "U+1F1F9U+1F1F9",
		EnName:  "Trinidad&Tobago",
		Emoji:   "🇹🇹",
		CnName:  "特立尼达和多巴哥",
	},
	{
		Code:    "TW",
		Unicode: "U+1F1F9U+1F1FC",
		EnName:  "Taiwan",
		Emoji:   "🇹🇼",
		CnName:  "台湾省",
	},
	{
		Code:    "TZ",
		Unicode: "U+1F1F9U+1F1FF",
		EnName:  "Tanzania",
		Emoji:   "🇹🇿",
		CnName:  "坦桑尼亚",
	},
	{
		Code:    "UA",
		Unicode: "U+1F1FAU+1F1E6",
		EnName:  "Ukraine",
		Emoji:   "🇺🇦",
		CnName:  "乌克兰",
	},
	{
		Code:    "UG",
		Unicode: "U+1F1FAU+1F1EC",
		EnName:  "Uganda",
		Emoji:   "🇺🇬",
		CnName:  "乌干达",
	},
	{
		Code:    "US",
		Unicode: "U+1F1FAU+1F1F8",
		EnName:  "UnitedStates",
		Emoji:   "🇺🇸",
		CnName:  "美国",
	},
	{
		Code:    "UY",
		Unicode: "U+1F1FAU+1F1FE",
		EnName:  "Uruguay",
		Emoji:   "🇺🇾",
		CnName:  "乌拉圭",
	},
	{
		Code:    "UZ",
		Unicode: "U+1F1FAU+1F1FF",
		EnName:  "Uzbekistan",
		Emoji:   "🇺🇿",
		CnName:  "乌兹别克斯坦",
	},
	{
		Code:    "VC",
		Unicode: "U+1F1FBU+1F1E8",
		EnName:  "St.Vincent&Grenadines",
		Emoji:   "🇻🇨",
		CnName:  "圣文森特",
	},
	{
		Code:    "VE",
		Unicode: "U+1F1FBU+1F1EA",
		EnName:  "Venezuela",
		Emoji:   "🇻🇪",
		CnName:  "委内瑞拉",
	},
	{
		Code:    "VN",
		Unicode: "U+1F1FBU+1F1F3",
		EnName:  "Vietnam",
		Emoji:   "🇻🇳",
		CnName:  "越南",
	},
	{
		Code:    "YE",
		Unicode: "U+1F1FEU+1F1EA",
		EnName:  "Yemen",
		Emoji:   "🇾🇪",
		CnName:  "也门",
	},
	{
		Code:    "ZA",
		Unicode: "U+1F1FFU+1F1E6",
		EnName:  "SouthAfrica",
		Emoji:   "🇿🇦",
		CnName:  "南非",
	},
	{
		Code:    "ZM",
		Unicode: "U+1F1FFU+1F1F2",
		EnName:  "Zambia",
		Emoji:   "🇿🇲",
		CnName:  "赞比亚",
	},
	{
		Code:    "ZW",
		Unicode: "U+1F1FFU+1F1FC",
		EnName:  "Zimbabwe",
		Emoji:   "🇿🇼",
		CnName:  "津巴布韦",
	},
}
