name: Build

on:
  release:
    types:
      - published
      - unpublished
      - created
      - edited
      - prereleased
      - released
  push:
    branches: [ test ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - run: make build
