name: Go

on:
  push:
    branches: [ test ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Golang CGO cross compiler
      uses: crazy-max/ghaction-xgo@v1.6.1
      with:
        go-version: 1.16

    - name: Build
      run: go build ./cmd/windows.go

