name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.2

    - name: Build
      run: CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -ldflags '-s -w' ./cmd/windows.go
